---
- name: Generate SSH Key pair for template in "{{ ssh_folder }}"
  community.crypto.openssh_keypair:
    path: "{{ ssh_folder }}/id_ed25519"
    type: ed25519
    comment: initial_template_key_generated_by_packer

- name: Slurp contents of public key
  ansible.builtin.slurp: 
    src: "{{ ssh_folder }}/id_ed25519.pub"
  register: slurped_pubkey

- name: Decode slurped public key and store as fact
  ansible.builtin.set_fact:
    pubkey: "{{ slurped_pubkey.content | b64decode | trim }}"

- name: Generate password hash from password
  ansible.builtin.shell: openssl passwd -6 -salt xyz {{password}}
  register: gen_hashed_password
